using System.Windows;

namespace GMCraftTableEditor;

/// <summary>
/// Управляет локализацией приложения (ru/en).
/// Все строки хранятся в коде — то же самое что ThemeManager для тем.
/// XAML использует {DynamicResource S.KeyName}.
/// </summary>
public static class LanguageManager
{
    public static bool IsRussian { get; private set; } = true;
    public static string CurrentLanguage => IsRussian ? "ru" : "en";

    // ── Русские строки ───────────────────────────────────────────────────────
    private static readonly (string Key, string Value)[] Russian =
    {
        // Навигация
        ("S.Nav.Craft",            "КРАФТ"),
        ("S.Nav.Recipes",          "Рецепты"),
        ("S.Nav.GmConfig",         "GM Config"),
        ("S.Nav.Quest",            "КВЕСТ СИСТЕМА"),
        ("S.Nav.Quests",           "Квесты"),
        ("S.Nav.NPC",              "NPC"),
        ("S.Nav.Loot",             "Пресеты лута"),
        ("S.Nav.Triggers",         "Триггеры / Маппинг"),
        ("S.Nav.Player",           "Прогресс игрока"),
        ("S.Nav.Medicine",         "МЕДИЦИНА"),
        ("S.Nav.MedicineConfig",   "Medicine Config"),
        ("S.Nav.AbilityConfig",    "Ability Config"),
        ("S.Nav.Food",             "ЕДА"),
        ("S.Nav.LiquidConfig",     "Liquid Config"),
        ("S.Nav.FoodConfig",       "Food Config"),
        ("S.Nav.Mining",           "МАЙНИНГ"),
        ("S.Nav.MineRock",         "MineRock Config"),
        ("S.Nav.RockPoints",       "Rock Points"),
        ("S.Nav.Settings",         "НАСТРОЙКИ"),
        ("S.Nav.Map",              "Карта"),

        // Главное окно — заголовок и тема
        ("S.App.Title",            "GM Mod Config Editor"),
        ("S.Theme.Label",          "Тема"),
        ("S.Theme.Dark",           "🌙 Тёмная"),
        ("S.Theme.Light",          "☀ Светлая"),
        ("S.Lang.Button",          "EN"),

        // Общие кнопки
        ("S.Btn.Open",             "📂 Открыть"),
        ("S.Btn.Save",             "💾 Сохранить"),
        ("S.Btn.SaveItem",         "💾 Сохранить item"),
        ("S.Btn.SaveTier",         "💾 Сохранить тир"),
        ("S.Btn.SavePreset",       "💾 Пресет"),
        ("S.Btn.Add",              "+ Добавить"),
        ("S.Btn.Delete",           "Удалить"),
        ("S.Btn.Edit",             "Редактировать"),
        ("S.Btn.Copy",             "Копировать"),
        ("S.Btn.Cancel",           "Отмена"),
        ("S.Btn.Save2",            "Сохранить"),
        ("S.Btn.OpenJson",         "Открыть JSON"),
        ("S.Btn.SaveJson",         "Сохранить JSON"),
        ("S.Btn.OpenMap",          "🗺  Открыть карту"),
        ("S.Btn.OnMap",            "🗺 На карте"),
        ("S.Btn.Check",            "✓ Проверить"),
        ("S.Btn.CheckRecipes",     "Проверить рецепты"),
        ("S.Btn.Search",           "🔍 Ctrl+F"),
        ("S.Btn.Destroy",          "Уничтожить"),

        // Статус
        ("S.Status.Ready",         "Готово"),
        ("S.Status.Unsaved",       "● Несохранённые изменения"),
        ("S.DoubleClickHint",      "✎ Двойной клик — открыть редактор"),

        // Страница рецептов
        ("S.Recipe.AddRecipe",     "+ Рецепт"),
        ("S.Recipe.AddIngr",       "+ Ингредиент"),
        ("S.Recipe.BasicInfo",     "Основная информация"),
        ("S.Recipe.ResultTime",    "Результат и время"),
        ("S.Recipe.Blueprint",     "Чертёж и навык"),
        ("S.Recipe.Flags",         "Флаги (0/1)"),
        ("S.Recipe.Params",        "Параметры"),
        ("S.Recipe.Tools",         "Инструменты TOOLS"),
        ("S.Recipe.Kits",          "Наборы NEEDS_KIT_ITEMS"),
        ("S.Recipe.Special",       "Спец. предметы"),
        ("S.Recipe.Ingredients",   "Ингредиенты INGRIDIENTS"),
        ("S.Recipe.Result",        "Результат"),
        ("S.Recipe.ToIngredient",  "→ В ингредиент"),
        ("S.Recipe.ToTool",        "→ В инструмент"),
        ("S.Recipe.ToResult",      "→ В результат"),
        ("S.Recipe.ToBlueprint",   "→ В чертёж"),

        // Страница квестов
        ("S.Quest.AddQuest",       "+ Квест"),
        ("S.Quest.AddTarget",      "+ Цель"),
        ("S.Quest.AddReward",      "+ Награда"),
        ("S.Quest.Targets",        "TARGETS — Цели"),
        ("S.Quest.Rewards",        "REWARDS — Награды"),
        ("S.Quest.DescFull",       "DESCRIPTION (полное)"),
        ("S.Quest.RepSchedule",    "Репутация / Расписание"),
        ("S.Quest.Progress",       "Прогресс целей"),
        ("S.Quest.TypeHint",       "1 — Убийство"),
        ("S.Quest.Type1",          "1 — Убийство"),
        ("S.Quest.Type2",          "2 — Поиск"),
        ("S.Quest.Type3",          "3 — Поиск и доставка NPC"),
        ("S.Quest.Type4",          "4 — Доставка от NPC"),
        ("S.Quest.Type5",          "5 — Крафт"),
        ("S.Quest.Type6",          "6 — Рыболовство"),
        ("S.Quest.Type7",          "7 — Охота"),
        ("S.Quest.Type8",          "8 — Садоводство"),
        ("S.Quest.Type9",          "9 — Исследование"),
        ("S.Quest.Type10",         "10 — Поиск схрона"),
        ("S.Quest.Type11",         "11 — Действие"),
        ("S.Quest.Type12",         "12 — Зачистка зоны"),
        ("S.Quest.Type13",         "13 — Зачистка объекта"),
        ("S.Quest.Type14",         "14 — Слесарный стол"),

        // Страница NPC
        ("S.NPC.AddNPC",           "+ NPC"),
        ("S.NPC.AddGroup",         "+ Группа"),
        ("S.NPC.AddDialog",        "+ Диалог"),
        ("S.NPC.Attachments",      "ATTACHMENTS — Экипировка NPC"),
        ("S.NPC.DialogSettings",   "DIALOG_SETTINGS — Диалоги"),
        ("S.NPC.CoordName",        "Координаты и название"),

        // Страница лута
        ("S.Loot.AddPreset",       "+ Пресет"),
        ("S.Loot.AddItem",         "+ Предмет"),
        ("S.Loot.StashPos",        "STASH_POSITIONS — Позиции схронов"),
        ("S.Loot.ItemsList",       "ITEMS_LIST — Предметы в схроне"),
        ("S.Loot.CostQuest",       "COST_QUEST — Стоимость получения"),
        ("S.Loot.Recipes",         "RECIPES — Плавка"),
        ("S.Loot.Wash",            "WASH_ARRAY — Промывка"),
        ("S.Loot.WashSettings",    "WASH_SETTINGS — Промывка"),
        ("S.Loot.Extraction",      "EXTRACTION_ARRAY — Руды"),
        ("S.Loot.ExtSettings",     "EXTRACTION_SETTINGS — Добыча"),
        ("S.Loot.Timers",          "Таймеры и шансы"),
        ("S.Loot.ObjSettings",     "Настройки объекта"),
        ("S.Loot.StashTiers",      "Тиры схронов"),
        ("S.Loot.StashPositions",  "Позиции схронов"),

        // Страница триггеров
        ("S.Trig.AddTrigger",      "+ Триггер"),
        ("S.Trig.AddItem2",        "+ Item"),
        ("S.Trig.TrigSettings",    "TRIGGER_SETTINGS — Зоны спавна зомби"),
        ("S.Trig.MappingSettings", "MAPPING_SETTINGS — Группы маппинга"),
        ("S.Trig.SpawnPos",        "POSITION — Позиции спавна (X Y Z)"),
        ("S.Trig.PosParams",       "Параметры позиции"),

        // Страница игрока
        ("S.Player.QuestsRep",     "Квесты и репутация"),
        ("S.Player.InProgress",    "Квесты в процессе:"),
        ("S.Player.Completed",     "Выполненные квесты:"),
        ("S.Player.Failed",        "Проваленные квесты:"),
        ("S.Player.Reputation",    "Репутация:"),

        // Таблицы / общие заголовки колонок
        ("S.Col.Name",             "Название"),
        ("S.Col.Category",         "Категория"),
        ("S.Col.Description",      "Описание"),
        ("S.Col.Count",            "Кол-во"),
        ("S.Col.AICount",          "Кол-во AI"),
        ("S.Col.Position",         "Позиция"),
        ("S.Col.Key",              "Ключ"),
        ("S.Col.Comment",          "Комментарий"),
        ("S.Col.Mod",              "Мод"),
        ("S.Col.Objects",          "Объектов"),
        ("S.Col.Answers",          "Ответов"),
        ("S.Col.Objects2",         "Объекты"),
        ("S.Col.Zones",            "Зоны"),
        ("S.Col.Delay",            "Задержка"),
        ("S.Col.Show",             "Показ (сек)"),
        ("S.Col.Radius",           "Радиус"),
        ("S.Col.RadiusAI",         "Радиус AI"),
        ("S.Col.Notification",     "Уведомление"),
        ("S.Col.Qty",              "Кол-во"),
        ("S.Col.MinMax",           "Min/Max Count"),
        ("S.Col.LiquidType",       "Тип жидкости"),
        ("S.Col.Energy",           "Энергия"),
        ("S.Col.Damage",           "Урон здоровью"),
        ("S.Col.Type",             "Тип (1-14)"),
        ("S.Col.ID",               "ID"),
        ("S.Col.ClassName",        "ClassName"),
        ("S.Col.Map",              "MAP"),
        ("S.Col.TextHigh",         "Текст (выс.)"),
        ("S.Col.TextNorm",         "Текст (норм.)"),
        ("S.Col.TextLow",          "Текст (низк.)"),

        // Страница настроек
        ("S.Settings.General",     "Общие настройки"),
        ("S.Settings.GlobalNPC",   "GM_ABILITY_CONFIG — Настройки системы навыков"),
        ("S.Settings.Blacksmith",  "Blacksmith бонусы (ABILITY)"),
        ("S.Settings.AdminList",   "AdminList (SteamID64, по одному на строке)"),
        ("S.Settings.PresetList",  "PresetList (по одному на строке)"),
        ("S.Settings.FryingPan",   "FryingPan Items"),
        ("S.Settings.IRP",         "IRP Items"),
        ("S.Settings.ObjectCount", "Объектов"),
        ("S.Settings.ProjectPath", "Путь к проекту"),
        ("S.Settings.Browse",      "Обзор..."),
        ("S.Settings.Language",    "Язык"),
        ("S.Settings.Apply",       "Применить"),

        // Окно настроек проекта (первый запуск)
        ("S.Setup.Title",          "Настройка проекта"),
        ("S.Setup.Description",    "Укажите папку вашего DayZ проекта (где лежат profiles или мод-папки). Приложение найдёт GM_Config автоматически."),
        ("S.Setup.SelectFolder",   "Выбрать папку"),
        ("S.Setup.NotFound",       "GM_Config не найден в указанной папке. Убедитесь что путь правильный."),
        ("S.Setup.Continue",       "Продолжить"),
        ("S.Setup.Skip",           "Пропустить"),

        // Workshop Import
        ("S.Workshop.Title",       "Импорт classnames из Workshop"),
        ("S.Workshop.Folder",      "Папка !Workshop"),
        ("S.Workshop.Browse",      "Выбрать"),
        ("S.Workshop.Find",        "Найти моды"),
        ("S.Workshop.Found",       "Найденные моды"),
        ("S.Workshop.Log",         "Лог"),
        ("S.Workshop.Scan",        "Сканировать выбранные"),
        ("S.Workshop.Close",       "Закрыть"),

        // GM Config Window
        ("S.GmConfig.Title",       "GM Config Editor"),
        ("S.GmConfig.OpenCraft",   "Открыть GM_CRAFTTABLE_CONFIG"),
        ("S.GmConfig.SaveCraft",   "Сохранить GM_CRAFTTABLE_CONFIG"),
        ("S.GmConfig.OpenAccess",  "Открыть GM_ACCESS_CONFIG"),
        ("S.GmConfig.SaveAccess",  "Сохранить GM_ACCESS_CONFIG"),
        ("S.GmConfig.Categories",  "Категории"),
        ("S.GmConfig.AddCategory", "+ Добавить категорию"),
        ("S.GmConfig.DelCategory", "Удалить категорию"),
        ("S.GmConfig.Tables",      "Столы"),
        ("S.GmConfig.AddTable",    "+ Добавить стол"),
        ("S.GmConfig.DelTable",    "Удалить стол"),
        ("S.GmConfig.Admins",      "Админы"),
        ("S.GmConfig.AddAdmin",    "+ Добавить админа"),
        ("S.GmConfig.DelAdmin",    "Удалить админа"),

        // Global Search
        ("S.Search.Title",         "Глобальный поиск"),
        ("S.Search.Find",          "🔍 Найти"),
        ("S.Search.Clear",         "✕ Очистить"),
        ("S.Search.SearchIn",      "Искать в:"),
        ("S.Search.Recipes",       "Рецепты"),
        ("S.Search.Database",      "Справочник"),
        ("S.Search.Quests",        "Квесты"),
        ("S.Search.NPC",           "NPC"),
        ("S.Search.Loot",          "Пресеты лута"),
        ("S.Search.Mods",          "Моды (медицина/еда/майнинг)"),
        ("S.Search.ColSection",    "Раздел"),
        ("S.Search.ColField",      "Поле"),
        ("S.Search.ColValue",      "Значение"),
        ("S.Search.ColFile",       "Файл"),
        ("S.Search.GoTo",          "Перейти →"),
        ("S.Search.Hint",          "Введите запрос и нажмите Enter или кнопку Найти"),

        // Validation Window
        ("S.Validation.Title",     "Проверка ошибок"),
        ("S.Validation.Recheck",   "🔄 Проверить снова"),
        ("S.Validation.Show",      "Показать:"),
        ("S.Validation.Errors",    "❌ Ошибки"),
        ("S.Validation.Warnings",  "⚠ Предупреждения"),
        ("S.Validation.Info",      "ℹ Инфо"),
        ("S.Validation.Section",   "Раздел:"),
        ("S.Validation.ColType",   "Тип"),
        ("S.Validation.ColSect",   "Раздел"),
        ("S.Validation.ColObj",    "Объект"),
        ("S.Validation.ColField",  "Поле"),
        ("S.Validation.ColProblem","Проблема"),
        ("S.Validation.GoTo",      "Перейти к ошибке →"),
        ("S.Validation.Export",    "Экспорт в TXT"),

        // Quest Target Dialog
        ("S.QTD.Title",            "Редактор цели квеста"),
        ("S.QTD.TypeQuest",        "Тип цели (TYPE_QUEST)"),
        ("S.QTD.TypeObject",       "TYPE_OBJECT"),
        ("S.QTD.Params",           "Параметры"),
        ("S.QTD.Hint",             "Подсказка по SETTINGS"),
        ("S.QTD.HintDefault",      "Выберите тип цели, чтобы увидеть подсказку."),
        ("S.QTD.Cancel",           "Отмена"),
        ("S.QTD.Save",             "Сохранить"),

        // Map Window
        ("S.Map.Title",            "GM Mod Config Editor — Карта"),
        ("S.Map.MapLabel",         "Карта:"),
        ("S.Map.NPC",              "🧑 NPC"),
        ("S.Map.Triggers",         "📍 Триггеры"),
        ("S.Map.Rocks",            "⛏ Камни"),
        ("S.Map.GoTo",             "Перейти"),
        ("S.Map.Refresh",          "🔄 Обновить"),
        ("S.Map.Hint",             "Наведи на карту..."),
        ("S.Map.X",                "X:"),
        ("S.Map.Z",                "Z:"),
        ("S.Map.Info",             "Интерактивная карта DayZ"),
        ("S.Map.Supports",         "Поддерживает 20+ карт: Chernarus, Livonia, Sakhal, Banov, DeerIsle и другие"),
        ("S.Map.Requires",         "Требуется Microsoft Edge WebView2 Runtime (обычно уже установлен в Windows 10/11)"),

        // Справочник предметов
        ("S.Items.Title",          "Справочник предметов"),
        ("S.Items.SteamID",        "SteamID:"),
        ("S.Items.Reputation",     "  Репутация:"),

        // ── Поля форм ────────────────────────────────────────────────────────────
        ("S.F.RecipeName", "Название рецепта"),
        ("S.F.Description", "Описание"),
        ("S.F.Category", "Категория"),
        ("S.F.Result", "Результат (предмет)"),
        ("S.F.ResultCount", "Кол-во результата"),
        ("S.F.ResultHealth", "Здоровье предмета"),
        ("S.F.TimeToCreate", "Время крафта (сек)"),
        ("S.F.GivePoints", "Очки опыта"),
        ("S.F.Plan", "Чертёж (classname)"),
        ("S.F.DamageToPlan", "Урон чертежу"),
        ("S.F.Ability", "Навык"),
        ("S.F.RequiredLevel", "Требуемый уровень"),
        ("S.F.WeaponRepair", "Ремонт оружия"),
        ("S.F.OtherRepair", "Ремонт предмета"),
        ("S.F.Dismantle", "Разборка"),
        ("S.F.RemoteCraft", "Дист. крафт"),
        ("S.F.NeedElectricity", "Нужен ток"),
        ("S.F.NeedSpecialItems", "Спец. предметы"),
        ("S.F.NeedCountKit", "Кол-во наборов"),
        ("S.F.ResultLiquid", "Результат (жидк.)"),
        ("S.F.LiquidType", "Тип жидкости"),
        ("S.F.MinConsumption", "Мин. потребление"),
        ("S.F.MaxConsumption", "Макс. потребление"),
        ("S.F.MinToolsDmg", "Мин. урон инстр."),
        ("S.F.MaxToolsDmg", "Макс. урон инстр."),
        ("S.F.MinAttachDmg", "Мин. урон прикр."),
        ("S.F.MaxAttachDmg", "Макс. урон прикр."),
        ("S.F.QuestName", "Название квеста"),
        ("S.F.DescShort", "Короткое описание"),
        ("S.F.ReloadQuest", "Перезапуск квеста"),
        ("S.F.TimeLimit", "Лимит времени"),
        ("S.F.CanCancel", "Можно отменить"),
        ("S.F.QuestRequired", "Требуемый квест"),
        ("S.F.Unavailable", "Недоступен"),
        ("S.F.RepReward", "Репутация (награда)"),
        ("S.F.RepPenalty", "Репутация (штраф)"),
        ("S.F.NeedRep", "Треб. репутация"),
        ("S.F.Unique", "Уникальный (0/1)"),
        ("S.F.HourStart", "Час начала"),
        ("S.F.MinStart", "Мин. начала"),
        ("S.F.HourFinish", "Час конца"),
        ("S.F.MinFinish", "Мин. конца"),
        ("S.F.NpcId", "ID NPC"),
        ("S.F.NpcType", "Тип NPC"),
        ("S.F.NpcName", "Имя NPC"),
        ("S.F.NpcNameAction", "Имя для действия"),
        ("S.F.NpcRole", "Роль NPC"),
        ("S.F.EnableTransfer", "Передача (0/1)"),
        ("S.F.Position", "Позиция (X Y Z)"),
        ("S.F.Orientation", "Ориентация"),
        ("S.F.NpcAvatarPath", "Путь к аватару"),
        ("S.F.QuestStart", "Начало квеста"),
        ("S.F.QuestFinish", "Конец квеста"),
        ("S.F.LowHighRep", "Мин/Макс репутация"),
        ("S.F.ConfigVersion", "Версия конфига"),
        ("S.F.Map", "Карта"),
        ("S.F.SaveAbilityOnDeath", "Сохр. очки при смерти"),
        ("S.F.EnablePeriodSave", "Период. сохранение"),
        ("S.F.PeriodAutoSave", "Авто-сохр. (сек)"),
        ("S.F.DeleteChestTimer", "Таймер удаления ящика"),
        ("S.F.RespawnLoot", "Респавн лута"),
        ("S.F.SpawnChest", "Спавн ящика"),
        ("S.F.SpawnItemStash", "Спавн схрона"),
        ("S.F.SpawnLootItemStash", "Спавн лут-схрона"),
        ("S.F.StashCord", "Координаты схрона"),
        ("S.F.DebugStash", "Дебаг схрона"),
        ("S.F.IgnoreChance", "Игнор. шанс"),
        ("S.F.ItemHealth", "Здоровье (-1=авто)"),
        ("S.F.ItemQuantity", "Кол-во (-1=авто)"),
        ("S.F.SpawnChance", "Шанс спавна (%)"),
        ("S.F.MaxSpawnChance", "Макс. шанс спавна"),
        ("S.F.MinSpawnChance", "Мин. шанс спавна"),
        ("S.F.TimerMax", "Таймер макс."),
        ("S.F.TimerMin", "Таймер мин."),
        ("S.F.ExplosionChance", "Шанс взрыва"),
        ("S.F.ExplosionDamage", "Урон взрыва"),
        ("S.F.ExplosionRadius", "Радиус взрыва"),
        ("S.F.GlovesDamage", "Урон перчаток"),
        ("S.F.BleedChance", "Шанс кровотечения"),
        ("S.F.CrateCan", "Ящик->жест. банка"),
        ("S.F.RespawnTime", "Время респавна (сек)"),
        ("S.F.Ingredient", "Ингредиент"),
        ("S.F.Quantity", "Количество"),
        ("S.F.Health01", "Здоровье (0-1)"),
        ("S.F.Chance01", "Шанс (0-1)"),
        ("S.F.ChanceLvl0", "Шанс ур.0"),
        ("S.F.ChanceLvl1", "Шанс ур.1"),
        ("S.F.ChanceLvl2", "Шанс ур.2"),
        ("S.F.ChanceLvl3", "Шанс ур.3"),
        ("S.F.QtyLvl0", "Кол-во ур.0"),
        ("S.F.QtyLvl1", "Кол-во ур.1"),
        ("S.F.QtyLvl2", "Кол-во ур.2"),
        ("S.F.QtyLvl3", "Кол-во ур.3"),
        ("S.F.Image", "Изображение"),
        ("S.F.Name", "Название"),
        ("S.F.ClassName", "ClassName"),
        ("S.F.Id", "ID"),
        ("S.F.Boiled", "Варёный (0/1)"),
        ("S.F.Fresh", "Свежий (0/1)"),
        ("S.F.Health", "Здоровье"),
        ("S.F.YHeight", "Y (высота)"),
        ("S.F.GlobalType", "Тип квеста (1-14)"),
        ("S.F.PresetListGaranted", "Список пресетов (гарант.)"),
        ("S.F.ItemsList", "Список предметов"),
        ("S.F.Monday", "Понедельник"),
        ("S.F.Tuesday", "Вторник"),
        ("S.F.Wednesday", "Среда"),
        ("S.F.Thursday", "Четверг"),
        ("S.F.Friday", "Пятница"),
        ("S.F.Saturday", "Суббота"),
        ("S.F.Sunday", "Воскресенье"),
        ("S.F.Count", "Количество"),
        ("S.F.DamageToIngredient", "Урон ингредиенту"),
        ("S.F.DamageToTools", "Урон инструменту"),
        ("S.F.DamageSpecialIngr", "Урон спец.ингр.(0/1)"),
        ("S.F.DeleteSpecialIngr", "Удалить спец.ингр.(0/1)"),
        ("S.F.DayQuest", "Суточный квест"),
        ("S.F.IsFinish", "Завершающий"),
        ("S.F.GroupId", "ID группы"),
        ("S.F.HasQty", "Есть кол-во"),
        ("S.F.NameOverride", "Замена имени"),
        ("S.F.NeedLiquid", "Треб. жидкость"),
        ("S.F.NeedLiq", "Треб. жидкость"),
        ("S.F.NpcDescription", "Описание NPC"),
        ("S.F.ResultQuantity", "Кол-во результата"),
        ("S.F.GeneralSettings", "Общие настройки"),
        ("S.F.MaxObjectsOnMap", "Макс. объектов на карте"),
        ("S.F.MinObjectsOnMap", "Мин. объектов на карте"),
        ("S.F.MeltingTemp", "Температура плавки"),
        ("S.F.MaxExtractionAmt", "Макс. добыча"),
        ("S.F.MinExtractionAmt", "Мин. добыча"),
        ("S.F.ExtractMaxQty", "Макс. кол-во добычи"),
        ("S.F.ExtractMinQty", "Мин. кол-во добычи"),
        ("S.F.DigDamageTools", "Урон инстр. при копке"),
        ("S.F.ChanceOfDig", "Шанс копки"),
        ("S.F.ChanceOfDigSand", "Шанс копки (песок)"),
        ("S.F.ChanceForWash", "Шанс промывки"),
        ("S.F.ChanceExtCoal", "Шанс добычи угля"),
        ("S.F.ChanceExtRare", "Шанс редкой добычи"),
        ("S.F.ChanceExtStone", "Шанс добычи камня"),
        ("S.F.RockBaseMax", "База камней макс."),
        // ── Колонки Medicine/Liquid таблиц ──────────────────────────────────────
        ("S.Col.Key",      "Ключ"),
        ("S.Col.Value",    "Значение"),
        ("S.Col.All",      "Все"),

    };

    // ── Английские строки ────────────────────────────────────────────────────
    private static readonly (string Key, string Value)[] English =
    {
        // Navigation
        ("S.Nav.Craft",            "CRAFT"),
        ("S.Nav.Recipes",          "Recipes"),
        ("S.Nav.GmConfig",         "GM Config"),
        ("S.Nav.Quest",            "QUEST SYSTEM"),
        ("S.Nav.Quests",           "Quests"),
        ("S.Nav.NPC",              "NPC"),
        ("S.Nav.Loot",             "Loot Presets"),
        ("S.Nav.Triggers",         "Triggers / Mapping"),
        ("S.Nav.Player",           "Player Progress"),
        ("S.Nav.Medicine",         "MEDICINE"),
        ("S.Nav.MedicineConfig",   "Medicine Config"),
        ("S.Nav.AbilityConfig",    "Ability Config"),
        ("S.Nav.Food",             "FOOD"),
        ("S.Nav.LiquidConfig",     "Liquid Config"),
        ("S.Nav.FoodConfig",       "Food Config"),
        ("S.Nav.Mining",           "MINING"),
        ("S.Nav.MineRock",         "MineRock Config"),
        ("S.Nav.RockPoints",       "Rock Points"),
        ("S.Nav.Settings",         "SETTINGS"),
        ("S.Nav.Map",              "Map"),

        // Main window
        ("S.App.Title",            "GM Mod Config Editor"),
        ("S.Theme.Label",          "Theme"),
        ("S.Theme.Dark",           "🌙 Dark"),
        ("S.Theme.Light",          "☀ Light"),
        ("S.Lang.Button",          "RU"),

        // Common buttons
        ("S.Btn.Open",             "📂 Open"),
        ("S.Btn.Save",             "💾 Save"),
        ("S.Btn.SaveItem",         "💾 Save item"),
        ("S.Btn.SaveTier",         "💾 Save tier"),
        ("S.Btn.SavePreset",       "💾 Preset"),
        ("S.Btn.Add",              "+ Add"),
        ("S.Btn.Delete",           "Delete"),
        ("S.Btn.Edit",             "Edit"),
        ("S.Btn.Copy",             "Copy"),
        ("S.Btn.Cancel",           "Cancel"),
        ("S.Btn.Save2",            "Save"),
        ("S.Btn.OpenJson",         "Open JSON"),
        ("S.Btn.SaveJson",         "Save JSON"),
        ("S.Btn.OpenMap",          "🗺  Open Map"),
        ("S.Btn.OnMap",            "🗺 On Map"),
        ("S.Btn.Check",            "✓ Validate"),
        ("S.Btn.CheckRecipes",     "Validate Recipes"),
        ("S.Btn.Search",           "🔍 Ctrl+F"),
        ("S.Btn.Destroy",          "Destroy"),

        // Status
        ("S.Status.Ready",         "Ready"),
        ("S.Status.Unsaved",       "● Unsaved changes"),
        ("S.DoubleClickHint",      "✎ Double click to open editor"),

        // Recipes page
        ("S.Recipe.AddRecipe",     "+ Recipe"),
        ("S.Recipe.AddIngr",       "+ Ingredient"),
        ("S.Recipe.BasicInfo",     "Basic Info"),
        ("S.Recipe.ResultTime",    "Result & Time"),
        ("S.Recipe.Blueprint",     "Blueprint & Skill"),
        ("S.Recipe.Flags",         "Flags (0/1)"),
        ("S.Recipe.Params",        "Parameters"),
        ("S.Recipe.Tools",         "Tools TOOLS"),
        ("S.Recipe.Kits",          "Kits NEEDS_KIT_ITEMS"),
        ("S.Recipe.Special",       "Special Items"),
        ("S.Recipe.Ingredients",   "Ingredients INGRIDIENTS"),
        ("S.Recipe.Result",        "Result"),
        ("S.Recipe.ToIngredient",  "→ To ingredient"),
        ("S.Recipe.ToTool",        "→ To tool"),
        ("S.Recipe.ToResult",      "→ To result"),
        ("S.Recipe.ToBlueprint",   "→ To blueprint"),

        // Quests page
        ("S.Quest.AddQuest",       "+ Quest"),
        ("S.Quest.AddTarget",      "+ Target"),
        ("S.Quest.AddReward",      "+ Reward"),
        ("S.Quest.Targets",        "TARGETS"),
        ("S.Quest.Rewards",        "REWARDS"),
        ("S.Quest.DescFull",       "DESCRIPTION (full)"),
        ("S.Quest.RepSchedule",    "Reputation / Schedule"),
        ("S.Quest.Progress",       "Target Progress"),
        ("S.Quest.TypeHint",       "1 — Kill"),
        ("S.Quest.Type1",          "1 — Kill"),
        ("S.Quest.Type2",          "2 — Search"),
        ("S.Quest.Type3",          "3 — Search & Deliver to NPC"),
        ("S.Quest.Type4",          "4 — Deliver from NPC"),
        ("S.Quest.Type5",          "5 — Craft"),
        ("S.Quest.Type6",          "6 — Fishing"),
        ("S.Quest.Type7",          "7 — Hunting"),
        ("S.Quest.Type8",          "8 — Gardening"),
        ("S.Quest.Type9",          "9 — Research"),
        ("S.Quest.Type10",         "10 — Find Stash"),
        ("S.Quest.Type11",         "11 — Action"),
        ("S.Quest.Type12",         "12 — Zone Clear"),
        ("S.Quest.Type13",         "13 — Object Clear"),
        ("S.Quest.Type14",         "14 — Locksmith Table"),

        // NPC page
        ("S.NPC.AddNPC",           "+ NPC"),
        ("S.NPC.AddGroup",         "+ Group"),
        ("S.NPC.AddDialog",        "+ Dialog"),
        ("S.NPC.Attachments",      "ATTACHMENTS — NPC Equipment"),
        ("S.NPC.DialogSettings",   "DIALOG_SETTINGS — Dialogs"),
        ("S.NPC.CoordName",        "Coordinates & Name"),

        // Loot page
        ("S.Loot.AddPreset",       "+ Preset"),
        ("S.Loot.AddItem",         "+ Item"),
        ("S.Loot.StashPos",        "STASH_POSITIONS"),
        ("S.Loot.ItemsList",       "ITEMS_LIST — Stash Items"),
        ("S.Loot.CostQuest",       "COST_QUEST — Acquisition Cost"),
        ("S.Loot.Recipes",         "RECIPES — Smelting"),
        ("S.Loot.Wash",            "WASH_ARRAY — Washing"),
        ("S.Loot.WashSettings",    "WASH_SETTINGS — Washing"),
        ("S.Loot.Extraction",      "EXTRACTION_ARRAY — Ores"),
        ("S.Loot.ExtSettings",     "EXTRACTION_SETTINGS — Mining"),
        ("S.Loot.Timers",          "Timers & Chances"),
        ("S.Loot.ObjSettings",     "Object Settings"),
        ("S.Loot.StashTiers",      "Stash Tiers"),
        ("S.Loot.StashPositions",  "Stash Positions"),

        // Triggers page
        ("S.Trig.AddTrigger",      "+ Trigger"),
        ("S.Trig.AddItem2",        "+ Item"),
        ("S.Trig.TrigSettings",    "TRIGGER_SETTINGS — Zombie Spawn Zones"),
        ("S.Trig.MappingSettings", "MAPPING_SETTINGS — Mapping Groups"),
        ("S.Trig.SpawnPos",        "POSITION — Spawn Positions (X Y Z)"),
        ("S.Trig.PosParams",       "Position Parameters"),

        // Player page
        ("S.Player.QuestsRep",     "Quests & Reputation"),
        ("S.Player.InProgress",    "Quests in progress:"),
        ("S.Player.Completed",     "Completed quests:"),
        ("S.Player.Failed",        "Failed quests:"),
        ("S.Player.Reputation",    "Reputation:"),

        // Table columns
        ("S.Col.Name",             "Name"),
        ("S.Col.Category",         "Category"),
        ("S.Col.Description",      "Description"),
        ("S.Col.Count",            "Count"),
        ("S.Col.AICount",          "AI Count"),
        ("S.Col.Position",         "Position"),
        ("S.Col.Key",              "Key"),
        ("S.Col.Comment",          "Comment"),
        ("S.Col.Mod",              "Mod"),
        ("S.Col.Objects",          "Objects"),
        ("S.Col.Answers",          "Answers"),
        ("S.Col.Objects2",         "Objects"),
        ("S.Col.Zones",            "Zones"),
        ("S.Col.Delay",            "Delay"),
        ("S.Col.Show",             "Show (sec)"),
        ("S.Col.Radius",           "Radius"),
        ("S.Col.RadiusAI",         "AI Radius"),
        ("S.Col.Notification",     "Notification"),
        ("S.Col.Qty",              "Qty"),
        ("S.Col.MinMax",           "Min/Max Count"),
        ("S.Col.LiquidType",       "Liquid Type"),
        ("S.Col.Energy",           "Energy"),
        ("S.Col.Damage",           "Health Damage"),
        ("S.Col.Type",             "Type (1-14)"),
        ("S.Col.ID",               "ID"),
        ("S.Col.ClassName",        "ClassName"),
        ("S.Col.Map",              "MAP"),
        ("S.Col.TextHigh",         "Text (high)"),
        ("S.Col.TextNorm",         "Text (norm)"),
        ("S.Col.TextLow",          "Text (low)"),

        // Settings page
        ("S.Settings.General",     "General Settings"),
        ("S.Settings.GlobalNPC",   "GM_ABILITY_CONFIG — Skill System Settings"),
        ("S.Settings.Blacksmith",  "Blacksmith Bonuses (ABILITY)"),
        ("S.Settings.AdminList",   "AdminList (SteamID64, one per line)"),
        ("S.Settings.PresetList",  "PresetList (one per line)"),
        ("S.Settings.FryingPan",   "FryingPan Items"),
        ("S.Settings.IRP",         "IRP Items"),
        ("S.Settings.ObjectCount", "Objects"),
        ("S.Settings.ProjectPath", "Project Path"),
        ("S.Settings.Browse",      "Browse..."),
        ("S.Settings.Language",    "Language"),
        ("S.Settings.Apply",       "Apply"),

        // Project Setup Window
        ("S.Setup.Title",          "Project Setup"),
        ("S.Setup.Description",    "Select your DayZ project folder (where profiles or mod folders are located). The app will find GM_Config automatically."),
        ("S.Setup.SelectFolder",   "Select Folder"),
        ("S.Setup.NotFound",       "GM_Config not found in the selected folder. Please check the path."),
        ("S.Setup.Continue",       "Continue"),
        ("S.Setup.Skip",           "Skip"),

        // Workshop Import
        ("S.Workshop.Title",       "Import classnames from Workshop"),
        ("S.Workshop.Folder",      "!Workshop Folder"),
        ("S.Workshop.Browse",      "Browse"),
        ("S.Workshop.Find",        "Find Mods"),
        ("S.Workshop.Found",       "Found Mods"),
        ("S.Workshop.Log",         "Log"),
        ("S.Workshop.Scan",        "Scan Selected"),
        ("S.Workshop.Close",       "Close"),

        // GM Config Window
        ("S.GmConfig.Title",       "GM Config Editor"),
        ("S.GmConfig.OpenCraft",   "Open GM_CRAFTTABLE_CONFIG"),
        ("S.GmConfig.SaveCraft",   "Save GM_CRAFTTABLE_CONFIG"),
        ("S.GmConfig.OpenAccess",  "Open GM_ACCESS_CONFIG"),
        ("S.GmConfig.SaveAccess",  "Save GM_ACCESS_CONFIG"),
        ("S.GmConfig.Categories",  "Categories"),
        ("S.GmConfig.AddCategory", "+ Add Category"),
        ("S.GmConfig.DelCategory", "Delete Category"),
        ("S.GmConfig.Tables",      "Tables"),
        ("S.GmConfig.AddTable",    "+ Add Table"),
        ("S.GmConfig.DelTable",    "Delete Table"),
        ("S.GmConfig.Admins",      "Admins"),
        ("S.GmConfig.AddAdmin",    "+ Add Admin"),
        ("S.GmConfig.DelAdmin",    "Delete Admin"),

        // Global Search
        ("S.Search.Title",         "Global Search"),
        ("S.Search.Find",          "🔍 Find"),
        ("S.Search.Clear",         "✕ Clear"),
        ("S.Search.SearchIn",      "Search in:"),
        ("S.Search.Recipes",       "Recipes"),
        ("S.Search.Database",      "Database"),
        ("S.Search.Quests",        "Quests"),
        ("S.Search.NPC",           "NPC"),
        ("S.Search.Loot",          "Loot Presets"),
        ("S.Search.Mods",          "Mods (medicine/food/mining)"),
        ("S.Search.ColSection",    "Section"),
        ("S.Search.ColField",      "Field"),
        ("S.Search.ColValue",      "Value"),
        ("S.Search.ColFile",       "File"),
        ("S.Search.GoTo",          "Go to →"),
        ("S.Search.Hint",          "Enter a query and press Enter or Find"),

        // Validation Window
        ("S.Validation.Title",     "Error Check"),
        ("S.Validation.Recheck",   "🔄 Recheck"),
        ("S.Validation.Show",      "Show:"),
        ("S.Validation.Errors",    "❌ Errors"),
        ("S.Validation.Warnings",  "⚠ Warnings"),
        ("S.Validation.Info",      "ℹ Info"),
        ("S.Validation.Section",   "Section:"),
        ("S.Validation.ColType",   "Type"),
        ("S.Validation.ColSect",   "Section"),
        ("S.Validation.ColObj",    "Object"),
        ("S.Validation.ColField",  "Field"),
        ("S.Validation.ColProblem","Problem"),
        ("S.Validation.GoTo",      "Go to error →"),
        ("S.Validation.Export",    "Export to TXT"),

        // Quest Target Dialog
        ("S.QTD.Title",            "Quest Target Editor"),
        ("S.QTD.TypeQuest",        "Target Type (TYPE_QUEST)"),
        ("S.QTD.TypeObject",       "TYPE_OBJECT"),
        ("S.QTD.Params",           "Parameters"),
        ("S.QTD.Hint",             "SETTINGS Hint"),
        ("S.QTD.HintDefault",      "Select a target type to see the hint."),
        ("S.QTD.Cancel",           "Cancel"),
        ("S.QTD.Save",             "Save"),

        // Map Window
        ("S.Map.Title",            "GM Mod Config Editor — Map"),
        ("S.Map.MapLabel",         "Map:"),
        ("S.Map.NPC",              "🧑 NPC"),
        ("S.Map.Triggers",         "📍 Triggers"),
        ("S.Map.Rocks",            "⛏ Rocks"),
        ("S.Map.GoTo",             "Go"),
        ("S.Map.Refresh",          "🔄 Refresh"),
        ("S.Map.Hint",             "Hover over the map..."),
        ("S.Map.X",                "X:"),
        ("S.Map.Z",                "Z:"),
        ("S.Map.Info",             "Interactive DayZ Map"),
        ("S.Map.Supports",         "Supports 20+ maps: Chernarus, Livonia, Sakhal, Banov, DeerIsle and more"),
        ("S.Map.Requires",         "Requires Microsoft Edge WebView2 Runtime (usually pre-installed on Windows 10/11)"),

        // Items database
        ("S.Items.Title",          "Items Database"),
        ("S.Items.SteamID",        "SteamID:"),
        ("S.Items.Reputation",     "  Reputation:"),

        // ── Form fields ──────────────────────────────────────────────────────────
        ("S.F.RecipeName", "Recipe Name"),
        ("S.F.Description", "Description"),
        ("S.F.Category", "Category"),
        ("S.F.Result", "Result (item)"),
        ("S.F.ResultCount", "Result Count"),
        ("S.F.ResultHealth", "Item Health"),
        ("S.F.TimeToCreate", "Craft Time (sec)"),
        ("S.F.GivePoints", "Give Points"),
        ("S.F.Plan", "Blueprint (classname)"),
        ("S.F.DamageToPlan", "Damage to Blueprint"),
        ("S.F.Ability", "Ability"),
        ("S.F.RequiredLevel", "Required Level"),
        ("S.F.WeaponRepair", "Weapon Repair"),
        ("S.F.OtherRepair", "Other Repair"),
        ("S.F.Dismantle", "Dismantle"),
        ("S.F.RemoteCraft", "Remote Craft"),
        ("S.F.NeedElectricity", "Need Electricity"),
        ("S.F.NeedSpecialItems", "Need Special Items"),
        ("S.F.NeedCountKit", "Kit Count"),
        ("S.F.ResultLiquid", "Result (liquid)"),
        ("S.F.LiquidType", "Liquid Type"),
        ("S.F.MinConsumption", "Min Consumption"),
        ("S.F.MaxConsumption", "Max Consumption"),
        ("S.F.MinToolsDmg", "Min Tools DMG"),
        ("S.F.MaxToolsDmg", "Max Tools DMG"),
        ("S.F.MinAttachDmg", "Min Attach DMG"),
        ("S.F.MaxAttachDmg", "Max Attach DMG"),
        ("S.F.QuestName", "Quest Name"),
        ("S.F.DescShort", "Short Description"),
        ("S.F.ReloadQuest", "Reload Quest"),
        ("S.F.TimeLimit", "Time Limit"),
        ("S.F.CanCancel", "Can Cancel"),
        ("S.F.QuestRequired", "Quest Required"),
        ("S.F.Unavailable", "Unavailable"),
        ("S.F.RepReward", "Rep Reward"),
        ("S.F.RepPenalty", "Rep Penalty"),
        ("S.F.NeedRep", "Need Rep"),
        ("S.F.Unique", "Unique (0/1)"),
        ("S.F.HourStart", "Hour Start"),
        ("S.F.MinStart", "Min Start"),
        ("S.F.HourFinish", "Hour Finish"),
        ("S.F.MinFinish", "Min Finish"),
        ("S.F.NpcId", "NPC ID"),
        ("S.F.NpcType", "NPC Type"),
        ("S.F.NpcName", "NPC Name"),
        ("S.F.NpcNameAction", "Name for Action"),
        ("S.F.NpcRole", "NPC Role"),
        ("S.F.EnableTransfer", "Enable Transfer"),
        ("S.F.Position", "Position (X Y Z)"),
        ("S.F.Orientation", "Orientation"),
        ("S.F.NpcAvatarPath", "Avatar Path"),
        ("S.F.QuestStart", "Quest Start"),
        ("S.F.QuestFinish", "Quest Finish"),
        ("S.F.LowHighRep", "Low/High Rep"),
        ("S.F.ConfigVersion", "Config Version"),
        ("S.F.Map", "Map"),
        ("S.F.SaveAbilityOnDeath", "Save Points on Death"),
        ("S.F.EnablePeriodSave", "Period Save"),
        ("S.F.PeriodAutoSave", "Auto Save (sec)"),
        ("S.F.DeleteChestTimer", "Delete Chest Timer"),
        ("S.F.RespawnLoot", "Respawn Loot"),
        ("S.F.SpawnChest", "Spawn Chest"),
        ("S.F.SpawnItemStash", "Spawn Item Stash"),
        ("S.F.SpawnLootItemStash", "Spawn Loot Stash"),
        ("S.F.StashCord", "Stash Coords"),
        ("S.F.DebugStash", "Debug Stash"),
        ("S.F.IgnoreChance", "Ignore Chance"),
        ("S.F.ItemHealth", "Health (-1=auto)"),
        ("S.F.ItemQuantity", "Qty (-1=auto)"),
        ("S.F.SpawnChance", "Spawn Chance (%)"),
        ("S.F.MaxSpawnChance", "Max Spawn Chance"),
        ("S.F.MinSpawnChance", "Min Spawn Chance"),
        ("S.F.TimerMax", "Timer Max"),
        ("S.F.TimerMin", "Timer Min"),
        ("S.F.ExplosionChance", "Explosion Chance"),
        ("S.F.ExplosionDamage", "Explosion Damage"),
        ("S.F.ExplosionRadius", "Explosion Radius"),
        ("S.F.GlovesDamage", "Gloves Damage"),
        ("S.F.BleedChance", "Bleed Chance"),
        ("S.F.CrateCan", "Crate->Eating Can"),
        ("S.F.RespawnTime", "Respawn Time (sec)"),
        ("S.F.Ingredient", "Ingredient"),
        ("S.F.Quantity", "Quantity"),
        ("S.F.Health01", "Health (0-1)"),
        ("S.F.Chance01", "Chance (0-1)"),
        ("S.F.ChanceLvl0", "Chance Lvl0"),
        ("S.F.ChanceLvl1", "Chance Lvl1"),
        ("S.F.ChanceLvl2", "Chance Lvl2"),
        ("S.F.ChanceLvl3", "Chance Lvl3"),
        ("S.F.QtyLvl0", "Qty Lvl0"),
        ("S.F.QtyLvl1", "Qty Lvl1"),
        ("S.F.QtyLvl2", "Qty Lvl2"),
        ("S.F.QtyLvl3", "Qty Lvl3"),
        ("S.F.Image", "Image"),
        ("S.F.Name", "Name"),
        ("S.F.ClassName", "ClassName"),
        ("S.F.Id", "ID"),
        ("S.F.Boiled", "Boiled (0/1)"),
        ("S.F.Fresh", "Fresh (0/1)"),
        ("S.F.Health", "Health"),
        ("S.F.YHeight", "Y (height)"),
        ("S.F.GlobalType", "Quest Type (1-14)"),
        ("S.F.PresetListGaranted", "Preset List (guaranteed)"),
        ("S.F.ItemsList", "Items List"),
        ("S.F.Monday", "Monday"),
        ("S.F.Tuesday", "Tuesday"),
        ("S.F.Wednesday", "Wednesday"),
        ("S.F.Thursday", "Thursday"),
        ("S.F.Friday", "Friday"),
        ("S.F.Saturday", "Saturday"),
        ("S.F.Sunday", "Sunday"),
        ("S.F.Count", "Count"),
        ("S.F.DamageToIngredient", "Damage to Ingredient"),
        ("S.F.DamageToTools", "Damage to Tools"),
        ("S.F.DamageSpecialIngr", "Damage Special Ingr."),
        ("S.F.DeleteSpecialIngr", "Delete Special Ingr."),
        ("S.F.DayQuest", "Day Quest"),
        ("S.F.IsFinish", "Is Finish"),
        ("S.F.GroupId", "Group ID"),
        ("S.F.HasQty", "Has Qty"),
        ("S.F.NameOverride", "Name Override"),
        ("S.F.NeedLiquid", "Need Liquid"),
        ("S.F.NeedLiq", "Need Liquid"),
        ("S.F.NpcDescription", "NPC Description"),
        ("S.F.ResultQuantity", "Result Quantity"),
        ("S.F.GeneralSettings", "General Settings"),
        ("S.F.MaxObjectsOnMap", "Max Objects on Map"),
        ("S.F.MinObjectsOnMap", "Min Objects on Map"),
        ("S.F.MeltingTemp", "Melting Temperature"),
        ("S.F.MaxExtractionAmt", "Max Extraction"),
        ("S.F.MinExtractionAmt", "Min Extraction"),
        ("S.F.ExtractMaxQty", "Extract Max Qty"),
        ("S.F.ExtractMinQty", "Extract Min Qty"),
        ("S.F.DigDamageTools", "Dig Damage Tools"),
        ("S.F.ChanceOfDig", "Chance of Dig"),
        ("S.F.ChanceOfDigSand", "Chance Dig Sand"),
        ("S.F.ChanceForWash", "Chance for Wash"),
        ("S.F.ChanceExtCoal", "Chance Coal"),
        ("S.F.ChanceExtRare", "Chance Rare"),
        ("S.F.ChanceExtStone", "Chance Stone"),
        ("S.F.RockBaseMax", "Rock Base Max"),
        // ── Medicine/Liquid table columns ────────────────────────────────────────
        ("S.Col.Key",      "Key"),
        ("S.Col.Value",    "Value"),
        ("S.Col.All",      "All"),

    };

    // ── Apply ────────────────────────────────────────────────────────────────

    public static void Apply(bool russian)
    {
        IsRussian = russian;
        var res = Application.Current.Resources;
        var strings = russian ? Russian : English;

        foreach (var (key, value) in strings)
            res[key] = value;
    }

    public static void Toggle() => Apply(!IsRussian);

    /// <summary>Вернуть строку по ключу (для использования в .cs коде).</summary>
    public static string Get(string key)
    {
        if (Application.Current?.Resources[key] is string s)
            return s;
        return key;
    }
}
